### ISSUE TITLE
Rock Paper Scissors

### ISSUE THREAD

**Issue by ryanrackemann** [ryanrackemann/ryanrackemann.github.io#35]
# Description  
The goal is to create a **Rock-Paper-Scissors** game as a static web project in a subsection (`/rps`) of the existing `ryanrackemann.com` website. This project will allow users to play a classic game of Rock-Paper-Scissors against the computer. It will demonstrate the fundamentals of web development using **HTML**, **CSS**, and **JavaScript**, while showcasing the efficiency of GitHub Copilot for writing modular and interactive code.

---

# Requirements

## 1. Basic Functionality
- A user interface with three buttons: "Rock", "Paper", and "Scissors".
- The computer's choice should be randomly generated each round.
- Compare the user’s choice with the computer's choice to determine the winner:
  - Rock beats Scissors.
  - Scissors beats Paper.
  - Paper beats Rock.
- Display the result of each round (Win, Lose, or Draw).
- Provide a reset button to clear the results and start a new game.

## 2. Scoring System
- Keep track of the user's score and the computer's score.
- Update the scores dynamically after each round.
- Display the scores prominently on the screen.

## 3. Styling
- Use CSS to style the game with a clean and modern design.
- Create visual feedback for the user’s choice (e.g., highlight the selected button).
- Use icons or images to represent Rock, Paper, and Scissors for better visual appeal.

## 4. Static Structure
Will be comprised of a new `/rps` directory which will host the following static web project files:
- **`index.html`**: The structure for the game UI.
- **`style.css`**: Styling for the game buttons, results, and score display.
- **`script.js`**: JavaScript for game logic and interactivity.

## 5. Extras (Optional)
- Add animations or sound effects for button clicks and results.
- Include a "Best of X Rounds" option where players can choose to play a set number of rounds (e.g., Best of 3, 5, or 7).
- Make the game responsive for mobile devices.

---

# Deliverables
- **`/rps/`**: The directory of the new game
- **`/rps/index.html`**: Contains the layout for the game buttons, scores, and result display.
- **`/rps/style.css`**: Defines the visual appearance of the game.
- **`/rps/script.js`**: Implements game logic, scorekeeping, and interactivity.

---

# Acceptance Criteria
- The game must be playable directly in a browser by opening `index.html`.
- The user should be able to:
  - Select their choice of Rock, Paper, or Scissors.
  - View the computer's choice.
  - See the outcome of each round and the updated scores.
- The game logic must correctly determine the winner of each round.
- The design must be polished and user-friendly.
- The project must remain static, using only HTML, CSS, and JavaScript.

**Comment by Yuvraj-Achrekar** [comment]
Should i attempt this ?

**Comment by ryanrackemann** [comment]
Hi, I apologize. I was using this to showcase how GitHub Workspaces. Thank you for your interest though. I'll close this out.
